# Generated by Django 5.1.4 on 2025-01-28 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rannaghoreprotidinapp', '0002_product_alter_userinfo_mobile_no_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('p_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.CharField(max_length=100)),
                ('brief_description', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media/products_img')),
                ('sku', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rannaghoreprotidinapp.products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rannaghoreprotidinapp.products'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
