# Generated by Django 5.1.4 on 2025-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rannaghoreprotidinapp', '0003_products_alter_cart_product_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/media/products_img'),
        ),
    ]
