# Generated by Django 5.1.4 on 2025-01-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rannaghoreprotidinapp', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='products_img'),
        ),
    ]
